DROP TABLE IF EXISTS pages CASCADE;
CREATE TABLE pages (id SERIAL PRIMARY KEY,url TEXT NOT NULL,is_scraping BOOLEAN NOT NULL DEFAULT 'false',created_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
Drop TABLE IF EXISTS links;
CREATE TABLE links(id SERIAL PRIMARY KEY,page_id INTEGER,url TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (page_id) REFERENCES pages(id));
